version: '3.3'
services:
  evosim-database:
    image: mysql:latest
    container_name: evosim-database
    hostname: evosim-database.docker
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'EVOSIM'
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PSSW}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT}
    ports:
      - ${DATABASE_PORT}:3306
    networks:
      - evosim-net
  evosim-server:
    container_name: evosim-server
    hostname: evosim-server.docker
    build:
      context: ./server/evosim-backend/
      dockerfile: ./Dockerfile
    command: npm run start:prod
    environment:
      DATABASE_HOST: evosim-database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PSSW: ${DATABASE_PSSW}
      PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"
    networks:
      - evosim-net
    volumes:
      - ${SERVER_SNAPSHOT_DIRECTORY}:/usr/src/app/server/snapshots
    depends_on:
      - evosim-database
    restart: unless-stopped
  evosim-client:
    container_name: evosim-client
    hostname: evosim-client.docker
    build:
      context: ./client/evosim-frontend/
      dockerfile: ./Dockerfile
    command: npm run start
    environment:
      HOST: ${CLIENT_HOST}
      PORT: ${CLIENT_PORT}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      - evosim-net
    depends_on:
      - evosim-server
    restart: unless-stopped
networks:
  evosim-net:
    driver: bridge